### ISSUE TITLE
Panel not showing in VS Code

### ISSUE THREAD

**Issue by brianhsimko** [petermekhaeil/vscode-tailwindcss-explorer#1]
Hello,
I'm getting the following message when opening the sidebar icon:
'An error occured while loading view: TailwindCssPanel'

I've tried uninstaling and reinstalling  to no affect.

**Comment by SpyShare** [comment]
> Hello,
> I'm getting the following message when opening the sidebar icon:
> 'An error occured while loading view: TailwindCssPanel'
> 
> I've tried uninstaling and reinstalling to no affect.

Yes Me Too Same message for tailwind

**Comment by petermekhaeil** [comment]
This error would appear if the `tailwindcss` npm package is not found in the workspace you have opened. Can you share your project's setup? It may help me fix the bug.

I have updated the extension to show a more meaningful error message if this occurs again.

**Comment by petermekhaeil** [comment]
I haven't heard back regarding this issue. I will close the issue. Thank you!
