### ISSUE TITLE
Explorer window empty

### ISSUE THREAD

**Issue by mollenbu** [petermekhaeil/vscode-tailwindcss-explorer#2]
I installed the latest version of Tailwind CSS Explorer on VSCode v1.58.0 and the "TAILWIND CSS EXPLORER" window is empty. 

Message, "Tailwind CSS cannot be found. Please check if it is installed correctly in your project."

I've tried restarting VSCode and re-installed the extension. Also, I don't see any configuration installation instructions out of the box. Seems straight forward that it should work after extension is installed. Am I missing something?

Please help!

Best

**Comment by marsglorious** [comment]
Same problem for me too.

**Comment by nullbio** [comment]
Same problem for me as well.

**Comment by nullbio** [comment]
I have this error as well.

**Comment by petermekhaeil** [comment]
This has been fixed in v0.7.0 (https://github.com/petermekhaeil/vscode-tailwindcss-explorer/pull/4)
https://marketplace.visualstudio.com/items/PeterMekhaeil.vscode-tailwindcss-explorer/changelog
