### ISSUE TITLE
The tailwindcss explorer window is empty

### ISSUE THREAD

**Issue by aliminurudeen** [petermekhaeil/vscode-tailwindcss-explorer#3]
The tailwindcss explorer window is empty, how do I make it show tailwind classes

**Comment by scott-fryxell** [comment]
Same problem.  what am I supposed to do to get it to work?

**Comment by petermekhaeil** [comment]
This has been fixed in v0.7.0 (https://github.com/petermekhaeil/vscode-tailwindcss-explorer/pull/4)
https://marketplace.visualstudio.com/items/PeterMekhaeil.vscode-tailwindcss-explorer/changelog
